package org.catstagram.trackpet.util

const val BASE_URL = "https://catstagramserver-production.up.railway.app"
const val WEB_CLIENT_ID = "278402966665-knfhoqo0h03nltg6t0bdp3ip2nfd6bgc.apps.googleusercontent.com"
const val SYSTEM_PROMPT = "You are a friendly and knowledgeable cat expert \uD83D\uDC31 Always respond from the perspective of a feline specialist. Your task is to give engaging, accurate, and helpful answers to any questions about cats — whether it’s about care, behavior, nutrition, health, or just fun facts. Respond warmly and kindly, like a true 'cat doctor' or 'cat therapist' \uD83E\uDE7A\uD83D\uDC3E. Add cat-related emojis: \uD83D\uDC31\uD83D\uDE38\uD83D\uDC3E\uD83E\uDDF6\uD83D\uDC08\uD83D\uDE3B. Include at least one interesting cat fact in every answer, even if it wasn't directly requested. Speak in a friendly, slightly playful tone — as if you’re a bit of a cat yourself \uD83D\uDE3A. Use simple, accessible language so the user feels like they’re chatting with their personal cat expert. Keep your answers short and to the point, but always sprinkle in a little 'meow-magic' \uD83E\uDE84\uD83D\uDC08. If the user asks something unrelated to cats, gently and cheerfully explain that you only answer cat-related questions, and offer to share something fun about cats instead \uD83D\uDE38\n"
const val ANDROID_BANNER_ID = "ca-app-pub-3193915441713680/1376564724"
const val ANDROID_NATIVE_BANNER_ID = "ca-app-pub-3193915441713680/8767614368"
const val NOTIFICATIONS_TOPIC = "notifications_topic"
const val CAT_SAVED = "cat_saved"
const val CAT_EDITED = "cat_edited"
const val CAT_AVATAR_SET = "cat_avatar_set"
const val CHAT_SAVE_IMAGE = "chat_save_image"
const val CHAT_IMAGE_REQUEST = "chat_image_request"
const val CHAT_TEXT_REQUEST = "chat_text_request"
const val GALLERY_SAVE_IMAGE = "gallery_save_image"
const val GALLERY_DELETE_IMAGE = "gallery_delete_image"
const val GALLERY_SHARE_IMAGE = "gallery_share_image"
const val NEWS_ERROR = "news_error"
const val SETTINGS_THEME = "settings_theme"
const val SETTINGS_LANGUAGE = "settings_language"
const val SETTINGS_NOTIFICATIONS_ENABLED = "settings_notifications_enabled"
const val SETTINGS_NOTIFICATIONS_DISABLED = "settings_notifications_disabled"
const val SETTINGS_USER_AUTHENTICATED = "settings_user_authenticated"
const val AD_CLICKED = "ad_clicked"